server:
  port: 8081
spring:
  application:
    name: OrdersApi
  datasource:
    url: jdbc:postgresql://localhost:5432/OrdersDatabase
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate:
      show_sql: true
      format_sql: true

#auth-server: http://auth-service/user/userinfo