spring:
  application:
    name: AuthApi
  datasource:
    url: jdbc:postgresql://db1:5433/AuthDatabase
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate:
      show_sql: true
      format_sql: true
